AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an S3 bucket for storing Lambda function code and ApiSchema.

Parameters:
  LambdaBucketName:
    Type: String
    Description: The name of the S3 bucket to create.

  SchemaImageBucketName:
    Type: String
    Description: The name of the S3 bucket to create.

Resources:
  LambdaFunctionCodeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref LambdaBucketName

  SchemaAndImageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref SchemaImageBucketName

Outputs:
  BucketNameOutput:
    Description: "Name of the S3 bucket for lambda"
    Value: !Ref LambdaFunctionCodeBucket
    Export:
      Name: LambdaBucketName

  BucketNameOutput2:
    Description: "Name of the S3 bucke for images and schemas"
    Value: !Ref SchemaAndImageBucket
    Export:
      Name: SchemaImageBucketName